export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const DATA_NEXT_PAGE = 'DATA_NEXT_PAGE';
export const DATA_PREV_PAGE = 'DATA_PREV_PAGE';
export const DATA_PAGE_SUCCESS = 'DATA_PAGE_SUCCESS';
export const DATA_PAGE_FAILURE = 'DATA_PAGE_FAILURE';

export default {
  FETCHING_DATA,
  FETCHING_DATA_SUCCESS,
  FETCHING_DATA_FAILURE,
  DATA_NEXT_PAGE,
  DATA_PREV_PAGE,
  DATA_PAGE_SUCCESS,
  DATA_PAGE_FAILURE,
};
